# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: design.gov.ro
author: GovITHub
email: design@ithub.gov.ro
description: > # this means to ignore newlines until "baseurl:"
  Ghid de proiectare a serviciilor gov.ro
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: govithub_ro
github_username:  gov-ithub

nav_main:
- page: Principii
  permalink: '/govro-design/'

- page: Componente
  permalink: '/govro-design/componente/'

- page: Utilizare
  permalink: '/govro-design/utilizare/'

nav_principii:
- page: Principii generale
  permalink: '/govro-design/'

- page: Principii de UX
  permalink: '/principii/ux'

- page: Principii de UI
  permalink: '/principii/ui'

nav_componente:
- page: Așezarea în pagină
  permalink: '#aezarea-n-pagin'

- page: Tipografia
  permalink: '#tipografia'

- page: Butoanele
  permalink: '#butoanele'

- page: Formularele
  permalink: '#formularele'

- page: Navigația
  permalink: '#navigaia'

- page: Alertele și notificările
  permalink: '#alertele-i-notificrile'

- page: Starea implicită
  permalink: '#starea-implicit'

- page: Utilitare
  permalink: '#utilitare'

- page: Șabloane
  permalink: '#abloane'

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
